### ISSUE TITLE
Live Recent Alerts months in a row undefined

### ISSUE THREAD

**Issue by hyflicker** [MJRLegends/MJRBot-Feedback#4]
On the dashboard under "Live Recent Alerts (beta)" on event message it reads "Just resubscribed to the channel using Twitch Prime for undefined months in a row, with a total of 18 months! Message: N/A". The N/A is fine if they didn't add a message but the undefined should be fixed.

**Comment by MJRLegends** [comment]
Thank you for your bug report, this issue has been fixed :)
